# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FM-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FM-Swift
pod 'Alamofire', '~> 4.0'
pod 'SnapKit', '~> 3.0.2'
pod 'SDCycleScrollView','~> 1.64'
pod 'HandyJSON', '~> 1.2.1'
pod 'SwiftyJSON'
pod 'DZNEmptyDataSet'
pod 'MJExtension'
  target 'FM-SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FM-SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
